export const majorBanks:{[key: string]: string} = {
    "044": "Access Bank",
    "057": "Zenith Bank",
    "011": "First Bank of Nigeria",
    "058": "Guaranty Trust Bank (GTBank)",
    "033": "United Bank for Africa (UBA)",
    "039": "Stanbic IBTC Bank",
    "070": "Fidelity Bank",
    "032": "Union Bank of Nigeria",
    "214": "First City Monument Bank (FCMB)",
    "050": "Ecobank Nigeria",
    "232": "Sterling Bank",
    "076": "Polaris Bank",
    "082": "Keystone Bank",
    "035": "Wema Bank",
    "030": "Heritage Bank",
    "215": "Unity Bank",
    "301": "Jaiz Bank",

    "063": "Diamond Bank",
    "100": "SunTrust Bank",
    "101": "Providus Bank",

  }

export const allBanks:{[key: string]: string} = {
  "C34": "9 Payment Service Bank",
  "A04": "Abbey Mortgage Bank",
  "F12": "Absu Microfinance Bank",
  "780": "Abu Microfinance Bank",
  "D80": "Abucoop Microfinance Bank",
  "044": "Access Bank Nigeria PLC",
  "063": "Access Bank PLC (Diamond)",
  "323": "Access Mobile",
  "B77": "Access Yello & Beta",
  "603": "Accion Microfinance Bank",
  "A07": "Addosser Microfinance Bank",
  "716": "Afekhafe Microfinance Bank",
  "014": "Afribank Nigeria PLC",
  "A09": "AG Mortgage Bank PLC",
  "D91": "Agosasa Microfinance Bank",
  "965": "Akpo Microfinance Bank",
  "D25": "Aku Microfinance Bank",
  "C73": "Akwa Savings and Loans Limited",
  "A11": "Al-Barakah Microfinance Bank",
  "A13": "Alert Microfinance Bank",
  "F25": "Alternative Bank Limited",
  "751": "Alvana Microfinance Bank",
  "E09": "Amegy Microfinance Bank",
  "964": "Amoye Microfinance Bank",
  "953": "Amucha Microfinance Bank",
  "885": "Aniocha Microfinance Bank",
  "A20": "Apple Microfinance Bank",
  "785": "Aso Savings and Loans",
  "712": "Assets Microfinance Bank",
  "D70": "Atbu MFB",
  "970": "Ave Maria Microfinance Bank",
  "969": "Avuenegbe Microfinance Bank",
  "880": "Awacash Microfinance Bank",
  "AMB": "Aztec Microfinance Bank",
  "F02": "Babura Microfinance Bank",
  "A25": "Baines Credit Microfinance Bank",
  "713": "Balogun Fulani Microfinance Bank",
  "E04": "Banc Corp Microfinance Bank",
  "958": "Beststar Microfinance Bank",
  "C14": "Bipc Microfinance Bank",
  "811": "Blueprint Investments Microfinance Bank",
  "D72": "Boi Microfinance Bank",
  "F13": "Borstal Microfinance Bank",
  "615": "Brent Mortgage Bank",
  "335": "Bridgeway Microfinance Bank",
  "A35": "Brightway Microfinance Bank",
  "883": "Briyth-Covenant Microfinance Bank",

  "F20": "Bunkure Microfinance Bank",
  "F16": "Canaan Microfinance Bank",
  "565": "Carbon",
  "886": "Cashbridge Microfinance Bank",
  "A36": "Cashconnect",
  "F24": "Cashrite Microfinance Bank",
  "C15": "Cellulant",
  "A37": "Cemcs Microfinance Bank",
  "010": "Central Bank of Nigeria",
  "B78": "Chams Mobile",
  "D87": "Chanelle Microfinance Bank",
  "694": "Chibueze Microfinance Bank",
  "D50": "Chukwunenye MFB",
  "023": "Citibank",
  "714": "Coalcamp Microfinance Bank",
  "A40": "Coastline Microfinance Bank",
  "D26": "Confidence Microfinance Bank",
  "693": "Coop Mortgage Bank",
  "A43": "Corestep Microfinance Bank",
  "C16": "Coronation Merchant Bank",
  "756": "Covenant Microfinance Bank",
  "A44": "Credit Afrique Microfinance Bank",
  "904": "Creditville Microfinance Bank",
  "802": "Crutech Microfinance Bank",
  "890": "CS Advance Finance Company Limited",
  "891": "Dal Microfinance Bank",
  "A45": "Davodani Microfinance Bank",
  "963": "Dignity Finance and Investment Limited",
  "F05": "Diobu Microfinance Bank",
  "C84": "Dot Microfinance Bank",
  "626": "Eartholeum",
  "D79": "Ebsu MFB",
  "050": "Ecobank Nigeria PLC",
  "B81": "Ecobank Xpress Account",
  "645": "Edfin Microfinance Bank",
  "895": "E-Finance",
  "A51": "Ek-Reliable Microfinance Bank",
  "972": "Enco Finance Company Ltd",
  "D19": "Enrich Microfinance Bank",
  "084": "Enterprise Bank Limited",
  "040": "Equitorial Trust Bank PLC",
  "A55": "Esan Microfinance Bank",
  "A56": "Eso-E Microfinance Bank",
  "317": "E-Tranzact",
  "D96": "Fame Microfinance Bank",
  "309": "FBN Mobile",
  "A70": "FBN Mortgage Bank (First Trust Mortgage Bank)",
  "C17": "FBNQuest Merchant Bank",
  "312": "FCMB Easy Account",

  "A61": "Federal University Dutse",
  "B85": "FET",
  "070": "Fidelity Bank PLC",
  "B86": "Fidelity Mobile",
  "C36": "Finca Microfinance Bank",
  "676": "Firmus Microfinance Bank",
  "011": "First Bank PLC",
  "214": "First City Monument Bank PLC",
  "085": "First Inland Bank PLC",
  "413": "Firsttrust Mortgage Bank PLC",
  "E05": "Flourish MFB",
  "B88": "Fortis Mobile",
  "501": "FSDH",
  "894": "Gabasawa Microfinance Bank",
  "A73": "Gateway Mortgage Bank",
  "902": "Gidauniyar Alheri Microfinance Bank",
  "703": "Girei Microfinance Bank",
  "884": "Global Initiative Microfinance Bank",
  "103": "Globus Bank",
  "A74": "Glory Microfinance Bank",
  "F07": "Gombe Microfinance Bank Limited",
  "B89": "GoMoney",
  "C85": "Goodnews Microfinance",
  "F11": "Greenacres Microfinance Bank",
  "A77": "Greenville Microfinance Bank",
  "C57": "Greenwich Merchant Bank",
  "B90": "GTBank Mobile Money",
  "058": "GTBank PLC",
  "A79": "GTI Microfinance Bank",
  "A81": "Haggai Mortgage Bank Limited",
  "B91": "Hedonmark Mobile",
  "030": "Heritage Bank",
  "C74": "Homebase Mortgage Bank",
  "800": "Hope Payment Service Bank",
  "D75": "Ibeto Microfinance Bank",
  "D24": "Ibolo Microfinance Bank",
  "D51": "Ibu-Aje Microfinance Bank",
  "D33": "IC-Global MFB",
  "A86": "Ikenne Microfinance Bank",
  "A87": "Ikire Microfinance Bank",
  "C94": "Ilaro Poly Microfinance Bank",
  "F10": "Ilora Microfinance",
  "A91": "Infinity Trust Mortgage Bank",
  "A93": "Isale Oyo Microfinance Bank",
  "867": "Island Microfinance Bank",
  "903": "Iyin Ekiti Microfinance Bank",
  "301": "Jaiz Bank",
  "D92": "Jessefield Microfinance",

  "971": "Kanopoly Microfinance Bank Limited",
  "082": "Keystone Bank PLC",
  "899": "KKU Microfinance Bank",
  "A97": "Kontagora Microfinance Bank",
  "910": "Kopo Kope Microfinance Bank",
  "A98": "Kuda Microfinance Bank",
  "594": "La Fayette Microfinance Bank",
  "C25": "Lagos Building Investment Company",
  "B01": "Lapo Microfinance Bank",
  "F17": "Leadcity Microfinance Bank",
  "898": "Leadremit Limited",
  "216": "Letshego MFB",
  "699": "Links Microfinance Bank",
  "C38": "Living Trust Mortgage Bank",
  "D21": "Lobrem Microfinance Bank",
  "303": "Lotus Bank",
  "897": "Lukefield Finance Company Limited",
  "900": "MAB Allianz Microfinance Bank",
  "879": "Mabinas Microfinance Bank",
  "906": "MacroD Microfinance Bank Limited",
  "893": "Madobi Microfinance Bank",
  "C86": "Manny Microfinance Bank",
  "B09": "Mayfair Microfinance Bank",
  "962": "Medef Microfinance Bank",
  "D28": "Mgbidi Microfinance Bank",
  "F23": "Michael Okpara Uniagric Microfinance Bank",
  "B12": "Microvis Microfinance Bank",
  "766": "Midland Microfinance Bank",
  "B94": "Mimo (Mkudi)",
  "882": "Minjibir Microfinance Bank",
  "B13": "Mint-Finex MFB",
  "B14": "Molusi Microfinance Bank",
  "C47": "Momo Payment Service Bank",
  "C39": "Moniepoint Microfinance Bank",
  "B17": "Mutual Benefits Microfinance Bank",
  "B18": "Mutual Trust Microfinance Bank",
  "598": "Nagarta Microfinance Bank",
  "807": "Nasarawa Microfinance Bank",
  "B21": "Neptune Microfinance Bank",
  "F18": "Nexim Bank",
  "999": "NIBSS",
  "B26": "NIRSAL Microfinance Bank",
  "561": "Nova Merchant Bank",
  "997": "Now Now Digital Systems",
  "B28": "NPF Microfinance Bank",
  "888": "Nsehe Microfinance Bank",
  "786": "Numo Microfinance Bank",

  "660": "Nurture Microfinance Bank",
  "D86": "Nwannegadi Microfinance Bank",
  "056": "Oceanic Bank Nigeria PLC",
  "F19": "Odoakpu Microfinance Bank Limited",
  "887": "Ohha Microfinance Bank",
  "F14": "Okengwe Microfinance Bank",
  "D61": "Olofin-Owena Microfinance Bank",
  "D60": "Oluchukwu Microfinance Bank",
  "C03": "Opay",
  "107": "Optimus Bank Limited",
  "881": "Oyan Microfinance Bank",
  "B98": "Paga",
  "B35": "Page MFBank",
  "B99": "PalmPay Limited",
  "104": "Parallex Bank Limited",
  "D89": "Parkway",
  "526": "Parrallllex",
  "C02": "Payattitude Online",
  "C67": "Paystack Payment Limited",
  "C40": "Peace Microfinance Bank",
  "B37": "PecanTrust Microfinance Bank",
  "D90": "Peniel Microfinance Bank",
  "B38": "Pennywise MFB",
  "076": "Polaris Bank",
  "809": "Polybadan Microfinance Bank",
  "D83": "Preeminent Microfinance Bank",
  "105": "Premiumtrust Bank",
  "B43": "Prestige Microfinance Bank",
  "752": "Pristine Divitis Microfinance Bank",
  "F06": "Prosperity Microfinance Bank",
  "101": "Providus Bank",
  "B44": "Purplemoney MFB",
  "F22": "Pyramid Microfinance Bank",
  "502": "Rand Merchant Bank",
  "956": "Rayyan Microfinance Bank",
  "B47": "Refuge Microfinance Bank",
  "707": "Rehoboth Microfinance Bank",
  "B49": "Reliance Microfinance Bank",
  "B50": "Renmoney Microfinance Bank",
  "B51": "Rephidim Microfinance Bank",
  "B52": "Richway Microfinance Bank",
  "720": "Rigo Microfinance Bank",
  "D73": "Rima Microfinance Bank",
  "F21": "Royal Blue Microfinance Bank",
  "B53": "Royal Exchange Microfinance Bank",
  "587": "Rubies MFB",
  "C41": "Shepherd Trust Microfinance Bank",
  "106": "Signature Bank",
  "830": "Simple Finance Limited",

  "D71": "SLS Microfinance Bank",
  "C60": "Smartcash Payment Service Bank",
  "F04": "Source Microfinance Bank",
  "B59": "Sparkle",
  "D76": "Spectrum Microfinance Bank",
  "C05": "Stanbic IBTC @ease wallet",
  "039": "Stanbic IBTC Bank PLC",
  "068": "Standard Chartered Bank Nigeria Limited",
  "709": "Standard Microfinance Bank",
  "C76": "STB Mortgage Bank",
  "232": "Sterling Bank PLC",
  "700": "Sunbeam Microfinance Bank",
  "F08": "Suntop Microfinance Bank",
  "100": "Suntrust Bank",
  "302": "Taj Bank",
  "F03": "Tangale Microfinance Bank",
  "C82": "Tangerine Money",
  "966": "Tasued Microfinance Bank",
  "779": "TCF Microfinance Bank",
  "C07": "Teasy Mobile",
  "968": "Tekla Factoring and Finance Limited",
  "677": "Think Finance Microfinance Bank",
  "102": "Titan Trust Bank",
  "889": "Total Trust Microfinance Bank",
  "957": "Trinity Financial",
  "569": "Trustbanc JB Microfinance Bank",
  "523": "Trustbond Mortgage (First Trust Mortgage)",
  "789": "U-C Microfinance Bank",
  "961": "Ummah Microfinance Bank",
  "F15": "Umuchukwu Microfinance Bank",
  "B66": "UNAAB Microfinance Bank",
  "F01": "Unifund Microfinance Bank Limited",
  "728": "Unilag Microfinance Bank",
  "705": "Unimaid Microfinance Bank",
  "032": "Union Bank of Nigeria PLC",
  "033": "United Bank for Africa PLC",
  "215": "Unity Bank PLC",
  "D95": "Uniuyo Microfinance Bank",
  "892": "Uzondu Microfinance Bank",
  "F26": "Vale Finance Limited",
  "B69": "VFD Microfinance Bank",
  "C08": "VTNetwork",
  "035": "Wema Bank PLC",
  "F09": "Xpress Wallet",
  "D63": "YCT Microfinance Bank",
  "057": "Zenith Bank PLC",
  "C10": "Zenith Mobile",
  "025": "ZInternet",

  }